ekf_node:
    ros__parameters:
        frequency: 50.0
        use_sim_time: True
        publish_tf: true
        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom
        odom0: /odom
        odom0_config: [true, true, false,  # x, y, z
                       false, false, true, # roll, pitch, yaw
                       true, true, false,  # vx, vy, vz
                       false, false, true] # vroll, vpitch, vyaw

