controller_manager:
  ros__parameters:
    update_rate: 1000  
    use_sim_time: True
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_velocity_controller:
  ros__parameters:
    joints:
      - wheel_1_joint
      - wheel_2_joint
      - wheel_3_joint
      - wheel_4_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
